CREATE TABLE menu2 (
    id_menu2 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nama_menu2 VARCHAR2(100) NOT NULL
);

ALTER TABLE menu2
ADD PRIMARY KEY (id_menu2);

ALTER TABLE menu2
ADD harga2 NUMBER;

INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM GORENG', 15000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM BAKAR', 12000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM GEPREK', 20000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM MADU', 17000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM CRISPY', 10000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM GULAI', 23000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM KALASAN', 32000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM KREMES', 15000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM RICA', 22000);
INSERT INTO menu2 (nama_menu2, harga2)
VALUES ('AYAM BUMBU RUJAK', 29000);

SELECT * FROM menu2;

CREATE TABLE buyer (
    id_buyer NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nama_buyer VARCHAR2(100) NOT NULL,
    email_buyer VARCHAR2(100) NOT NULL
);

ALTER TABLE buyer
ADD PRIMARY KEY (id_buyer);

INSERT INTO buyer (nama_buyer,email_buyer)
VALUES ('Jessica','jess@email.com');
INSERT INTO buyer (nama_buyer,email_buyer)
VALUES ('Amirah','amirah16@email.com');
INSERT INTO buyer (nama_buyer,email_buyer)
VALUES ('Paul','paulll@email.com');
INSERT INTO buyer (nama_buyer,email_buyer)
VALUES ('Ari','ari88@email.com');
INSERT INTO buyer (nama_buyer,email_buyer)
VALUES ('Rena','ren4@email.com');

SELECT * FROM buyer;

CREATE TABLE seller (
    id_seller NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nama_seller VARCHAR2(100) NOT NULL,
    gaji_seller NUMBER
);

ALTER TABLE seller
ADD PRIMARY KEY (id_seller);

INSERT INTO seller (nama_seller,gaji_seller)
VALUES ('Vina',850000);
INSERT INTO seller (nama_seller,gaji_seller)
VALUES ('Anwar',1000000);
INSERT INTO seller (nama_seller,gaji_seller)
VALUES ('Dodi',650000);

SELECT * FROM seller;

CREATE TABLE bill (
    id_bill NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_buyer NUMBER,
    id_seller NUMBER,
    waktu_pesan DATE,
    total NUMBER
);

ALTER TABLE bill
ADD PRIMARY KEY (id_bill);

ALTER TABLE bill
ADD CONSTRAINT fk_buyer
  FOREIGN KEY (id_buyer)
  REFERENCES buyer(id_buyer);
  
ALTER TABLE bill
ADD CONSTRAINT fk_seller
  FOREIGN KEY (id_seller)
  REFERENCES seller(id_seller);

INSERT INTO bill (id_buyer, id_seller,waktu_pesan,total)
VALUES (1,3,TO_DATE('16.11.2022','DD.MM.YYYY'),0);

SELECT * FROM bill;

CREATE TABLE detail(
    id_detail NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_bill NUMBER,
    id_menu2 NUMBER,
    kuantitas NUMBER
);


ALTER TABLE detail
ADD CONSTRAINT fk_bill
  FOREIGN KEY (id_bill)
  REFERENCES bill(id_bill);
  
ALTER TABLE detail
ADD CONSTRAINT fk_menu2
  FOREIGN KEY (id_menu2)
  REFERENCES menu2(id_menu2);
  
INSERT INTO detail (id_bill,id_menu2,kuantitas)
VALUES (1,3,4);

SELECT * FROM detail;

SELECT SUM(kuantitas*harga2) AS total
FROM bill
JOIN detail ON bill.id_bill = detail.id_bill 
JOIN menu2 ON menu2.id_menu2 = detail.id_menu2
WHERE bill.id_bill = 1;

UPDATE bill 
SET total = (
    SELECT SUM(kuantitas*harga2) AS total
    FROM bill
    JOIN detail ON bill.id_bill = detail.id_bill 
    JOIN menu2 ON menu2.id_menu2 = detail.id_menu2
    WHERE bill.id_bill = 1
)WHERE bill.id_bill = 1;

SELECT * FROM bill;

